from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True; dependencies=[]
    operations=[
        migrations.CreateModel(name="Candle",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("symbol",models.CharField(max_length=20)),("interval",models.CharField(max_length=8)),("open_time",models.DateTimeField()),("close_time",models.DateTimeField()),("open",models.DecimalField(decimal_places=8,max_digits=24)),("high",models.DecimalField(decimal_places=8,max_digits=24)),("low",models.DecimalField(decimal_places=8,max_digits=24)),("close",models.DecimalField(decimal_places=8,max_digits=24)),("volume",models.DecimalField(decimal_places=8,max_digits=30)),("is_closed",models.BooleanField(default=True))],options={"indexes":[models.Index(fields=["symbol","interval","-open_time"],name="signals_can_symbol_db0d11_idx")],"constraints":[models.UniqueConstraint(fields=("symbol","interval","open_time"),name="unique_candle")]}),
        migrations.CreateModel(name="AnalysisRun",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("symbol",models.CharField(max_length=20)),("interval",models.CharField(max_length=8)),("candle_close_time",models.DateTimeField()),("strategy_version",models.CharField(default="trend-v1",max_length=30)),("status",models.CharField(choices=[("rejected","Rejected"),("watch","Watch"),("confirmed","Confirmed"),("error","Error")],max_length=20)),("score",models.PositiveSmallIntegerField(default=0)),("reasons",models.JSONField(default=list)),("warnings",models.JSONField(default=list)),("features",models.JSONField(default=dict))],options={"constraints":[models.UniqueConstraint(fields=("symbol","interval","candle_close_time","strategy_version"),name="unique_analysis")]}),
        migrations.CreateModel(name="BacktestRun",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("symbol",models.CharField(max_length=20)),("interval",models.CharField(max_length=8)),("strategy_version",models.CharField(default="trend-v1",max_length=30)),("start",models.DateTimeField()),("end",models.DateTimeField()),("status",models.CharField(default="pending",max_length=20)),("parameters",models.JSONField(default=dict)),("metrics",models.JSONField(default=dict))]),
        migrations.CreateModel(name="MLModel",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=80)),("version",models.CharField(max_length=40,unique=True)),("artifact_path",models.CharField(max_length=255)),("created_at",models.DateTimeField(auto_now_add=True)),("training_start",models.DateTimeField()),("training_end",models.DateTimeField()),("metrics",models.JSONField(default=dict)),("feature_names",models.JSONField(default=list)),("active",models.BooleanField(default=False)),("approved",models.BooleanField(default=False))]),
        migrations.CreateModel(name="Signal",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("direction",models.CharField(default="long",max_length=8)),("entry_low",models.DecimalField(decimal_places=8,max_digits=24)),("entry_high",models.DecimalField(decimal_places=8,max_digits=24)),("stop_loss",models.DecimalField(decimal_places=8,max_digits=24)),("target_1",models.DecimalField(decimal_places=8,max_digits=24)),("target_2",models.DecimalField(decimal_places=8,max_digits=24)),("risk_reward",models.DecimalField(decimal_places=3,max_digits=8)),("confidence",models.PositiveSmallIntegerField()),("ml_probability",models.FloatField(blank=True,null=True)),("expires_at",models.DateTimeField()),("state",models.CharField(choices=[("active","Active"),("target1","Target 1"),("won","Won"),("stopped","Stopped"),("expired","Expired"),("invalidated","Invalidated")],default="active",max_length=20)),("created_at",models.DateTimeField(auto_now_add=True)),("resolved_at",models.DateTimeField(blank=True,null=True)),("analysis",models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,related_name="signal",to="signals.analysisrun"))]),
        migrations.CreateModel(name="SignalEvent",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("event_type",models.CharField(max_length=40)),("price",models.DecimalField(blank=True,decimal_places=8,max_digits=24,null=True)),("created_at",models.DateTimeField(auto_now_add=True)),("details",models.JSONField(default=dict)),("signal",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="events",to="signals.signal"))]),
    ]
